### ISSUE TITLE
That is no "PHP implementation of Google Route Boxer"

### ISSUE THREAD

**Issue by SventB** [bazo/route-boxer#1]
You just draw a direct line between the coordinates and draw boxes on that line.
Google Route Boxer draws boxes on a route.

**Comment by bazo** [comment]
ok, send a pull request

**Comment by bazo** [comment]
actually this lib doesn't draw anything, nor the original google implementation. you have to draw the boxes yourself

**Comment by SventB** [comment]
Hello,
thanks for the quick answer and sorry for being a little bit upset.
You're right, it draws no boxes. What I meant is, that Google RouteBoxer returns the coordinates for the boxes on a route but your PHP library acts different, it returns the coordinates for the boxes on a direct line between the given coordinates.
Perhaps I find a solution for this on my own.

**Comment by bazo** [comment]
are you passing it just two point? you need to give all the points on the route, which is exactly what google does. first it fetches the route from routing service then it passes the points to the route boxer. see the test.php file

**Comment by SventB** [comment]
Yes, I am passing two points. I understood, that I have to give all the points to routeboxer.
You're right, Google's RouteBoxer also expects a path...

I've solved this now, I use "overview_polyline", decode it with https://github.com/emcconville/google-map-polyline-encoding-tool and pass the coordinates to your routeboxer.

Sorry for blaming you! Are you interested in a full example, which you could put into the readme?

**Comment by bazo** [comment]
yes, send a pr

Dňa 24.9.2013, o 14:37, SventB notifications@github.com napísal:

**Comment by Thiyageshv** [comment]
Please brief me on how to start with this. I tried executing test.php file directly but its showing errors.

**Comment by bazo** [comment]
I have updated the readme. test.php executes just fine.

**Comment by raghavk92** [comment]
@bazo 1) i just wanted to ask how should i go about computing on the $boxes(array of Geotools\LatLngBounds object) on which DbLatLngs stored in the db are contained in a particular route's $boxes  --- i mean should i store the polyline in the database and everytime compute $boxes and then compare with DbLatLngs ..or.. should i store the decoded points which can be very large in number ..or..  should i store the $boxes object in the database ---  ? i dont know which one to and why?
2) can i even store the $boxes object and how should i?

Please help
thanks in advance
